### PR TITLE
fix drone

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
CI is missing Codecov token

**Comment by lunny** [comment]
I'm trying to set that token

**Comment by techknowlogick** [comment]
@lunny Did you set `Allow Pull Requests` for secret?

**Comment by lunny** [comment]
@techknowlogick you are right, done.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
