### PR TITLE
[WIP] add -r & -l to subcommand create (#12)

### PR DESCRIPTION
**Pull request by root360-AndreasUlm**
Signed-off-by: Andreas Ulm <andreas.ulm@root360.de>

### CODE REVIEW

**Comment by lunny** [comment]
The parent command `CmdReleases` has had these two flags?

**Comment by root360-AndreasUlm** [comment]
Yes it does already.

**Comment by root360-AndreasUlm** [comment]
Also when setting this flag before 'create'-subcommand it is recognized and works.

**Comment by root360-AndreasUlm** [comment]
I'm currently testing an approach to simplify using global flags.
I'll create a different PR with the implementation then we can discuss it.

**Comment by noerw** [comment]
I was confronted with this as well when implementing #6, and opted to move the extraction logic of global flags to the `initCommand()` function to avoid repetition, while allowing prefix or postfix flags for 1st level subcommands.
(This however requires that each command adds the respective flag itself, and works not well for 2nd level or deeper subcommands)

As discussed [here](https://github.com/urfave/cli/issues/191), subcommands inheriting global flags would be the solution, but was never implemented.
Generally I find https://github.com/spf13/cobra implements this correctly (and in general has better defaults) while providing a very similar interface to urfave/cli, so switching to that might be the simplest option, if we want this fixed properly.

**Comment by lafriks** [comment]
I would not mind against changing to cobra as that is what I usually use myself :)

**Comment by root360-AndreasUlm** [comment]
I started implementing Cobra. ( https://github.com/root360-AndreasUlm/tea/tree/12_switch_to_cobra )
There are some changes in the central flag handling required but the interface of Cobra is nice to use and the flag inheritence works in my current tests.
I'll switch all modules to Cobra and create a PR by the end of the week.

**Comment by techknowlogick** [comment]
I prefer we keep same cli lib as we can use flags from gitea itself in this lib and share code. This reduce duplication.

**Comment by lunny** [comment]
It seems rebase is not correct.

**Comment by root360-AndreasUlm** [comment]
> I prefer we keep same cli lib as we can use flags from gitea itself in this lib and share code. This reduce duplication.

The problem with the current cli lib is that we have to copy every global flag into every subcommand as the inheritence does not work correctly.
The only workaround to reduce redundant code I found so far is to create a variable containing a []cli.Flag{} with all global flags and append that to the flags of the subcommand (based on https://github.com/urfave/cli/issues/585).

@lunny I rebased the branch again on latest master. But I see the changes in README this PR want to do. Shall I create a new PR with cleaned changes?

**Comment by techknowlogick** [comment]
We had a similar issue with go-gitea/gitea, however you can see at this commit: https://github.com/go-gitea/gitea/commit/8d0d7bc28d517acc9ca98f0468d7ff2a4fdaf139#diff-7ddfb3e035b42cd70649cc33393fe32cR75 where we have default flags that append to all subcommands.

**Comment by root360-AndreasUlm** [comment]
is closed in favor of #26 implementation

**Pull request closed without merging**
